// Police Units Data
// Complete structure for all police divisions and their roles

import {
  faUserShield,
  faGraduationCap,
  faShieldAlt,
  faMotorcycle,
  faCar,
  faUserSecret,
  faHelicopter,
  faUserGraduate,
  faUserCog,
} from '@fortawesome/free-solid-svg-icons';

export const policeUnits = [
  {
    id: 1,
    name: 'Internal Affairs',
    icon: faUserShield,
    description: 'Internal affairs is for council only',
    supervisor: 'IA Director',
    leader: 'IA Investigator',
    members: 'IA Investigator',
    isCouncilOnly: true,
    color: '#af52de',
    badge: 'Council Only',
  },
  {
    id: 2,
    name: 'Academy & Training Division',
    icon: faGraduationCap,
    description: 'Responsible for training and certifying new officers',
    supervisor: 'Training Supervisor',
    leader: 'Training Leader',
    members: 'Training Officers',
    isCouncilOnly: false,
    color: '#007aff',
    badge: 'Training',
  },
  {
    id: 3,
    name: 'Patrol Division',
    icon: faShieldAlt,
    description: 'Primary law enforcement unit responsible for patrolling the city',
    supervisor: 'Patrol Supervisor',
    leader: 'Patrol Leader',
    members: 'Patrol Officers',
    isCouncilOnly: false,
    color: '#34c759',
    badge: 'Patrol',
  },
  {
    id: 4,
    name: 'Motorcycle Division',
    icon: faMotorcycle,
    description: 'Specialized unit using motorcycles for traffic and pursuit operations',
    supervisor: 'Motorcycle Supervisor',
    leader: 'Motorcycle Leader',
    members: 'Motorcycle Officers',
    isCouncilOnly: false,
    color: '#ff9500',
    badge: 'Traffic',
  },
  {
    id: 5,
    name: 'Interceptor Division',
    icon: faCar,
    description: 'High-speed pursuit unit equipped with interceptor vehicles',
    supervisor: 'Interceptor Supervisor',
    leader: 'Interceptor Leader',
    members: 'Interceptor Officers',
    isCouncilOnly: false,
    color: '#ff3b30',
    badge: 'Pursuit',
  },
  {
    id: 6,
    name: 'Criminal Investigation Division (CID)',
    icon: faUserSecret,
    description: 'Investigates serious crimes and conducts detective work',
    supervisor: 'CID Supervisor',
    leader: 'CID Leader',
    members: 'CID Detectives',
    isCouncilOnly: false,
    color: '#5856d6',
    badge: 'Detective',
  },
  {
    id: 7,
    name: 'Air Support Division',
    icon: faHelicopter,
    description: 'Provides aerial support with helicopters for surveillance and pursuit',
    supervisor: 'Air Support Supervisor',
    leader: 'Air Support Leader',
    members: 'Air Support Officers',
    isCouncilOnly: false,
    color: '#00c7be',
    badge: 'Air',
  },
  {
    id: 8,
    name: 'Trooper Division',
    icon: faUserGraduate,
    description: 'State-level law enforcement unit with high authority',
    supervisor: 'Trooper Supervisor',
    leader: 'Trooper Leader',
    members: 'Trooper Officers',
    isCouncilOnly: false,
    color: '#ff2d55',
    badge: 'Trooper',
  },
  {
    id: 9,
    name: 'Special Response Division (SRD)',
    icon: faUserCog,
    description: 'Elite unit for high-risk operations and tactical responses',
    supervisor: 'SRD Supervisor',
    leader: 'SRD Leader',
    members: 'SRD Officers',
    isCouncilOnly: false,
    color: '#ff6b6b',
    badge: 'Tactical',
  },
];

// Helper functions for units
export const getUnitById = (id) => policeUnits.find((unit) => unit.id === id);
export const getUnitsByCouncilOnly = () => policeUnits.filter((unit) => unit.isCouncilOnly);
export const getUnitsByBadge = (badge) => policeUnits.filter((unit) => unit.badge === badge);
export const getUnitCount = () => policeUnits.length;
export const getCouncilOnlyCount = () => policeUnits.filter((u) => u.isCouncilOnly).length;