// Police Ranks Data
// Complete police rank structure with officers

import {
  faCrown,
  faUserShield,
  faStar,
  faUserTie,
  faUserCheck,
  faUser,
  faGraduationCap,
} from '@fortawesome/free-solid-svg-icons';

export const policeRanks = [
  {
    id: 1,
    rank: 'Council',
    icon: faCrown,
    color: '#ffd700',
    bgColor: 'rgba(255, 215, 0, 0.15)',
    borderColor: '#ffd700',
    description: 'Supreme governing body',
    members: [
      { id: 1, name: '! RUSLAN111', badge: null, unit: 'Council' },
      { id: 2, name: 'Mario Guevara', badge: '100', unit: 'Council' },
      { id: 3, name: 'DIEGO WASHINGTON', badge: '110', unit: 'Council' },
    ],
  },
  {
    id: 2,
    rank: 'Chief of Police',
    icon: faUserShield,
    color: '#ff6b6b',
    bgColor: 'rgba(255, 107, 107, 0.15)',
    borderColor: '#ff6b6b',
    description: 'Highest ranking officer',
    members: [],
  },
  {
    id: 3,
    rank: 'Assistant Chief Police',
    icon: faUserShield,
    color: '#ff6b6b',
    bgColor: 'rgba(255, 107, 107, 0.12)',
    borderColor: '#ff6b6b',
    description: 'Second highest ranking officer',
    members: [],
  },
  {
    id: 4,
    rank: 'Deputy Chief Police',
    icon: faUserShield,
    color: '#ff6b6b',
    bgColor: 'rgba(255, 107, 107, 0.10)',
    borderColor: '#ff6b6b',
    description: 'Third highest ranking officer',
    members: [],
  },
  {
    id: 5,
    rank: 'Commander',
    icon: faStar,
    color: '#ff9500',
    bgColor: 'rgba(255, 149, 0, 0.15)',
    borderColor: '#ff9500',
    description: 'Commands multiple divisions',
    members: [{ id: 1, name: 'Max Payne', badge: null, unit: 'Command' }],
  },
  {
    id: 6,
    rank: 'Captain',
    icon: faStar,
    color: '#ff9500',
    bgColor: 'rgba(255, 149, 0, 0.12)',
    borderColor: '#ff9500',
    description: 'Leads a division',
    members: [{ id: 1, name: 'Emilio Grandé', badge: '101', unit: 'Patrol Division' }],
  },
  {
    id: 7,
    rank: 'Lieutenant',
    icon: faStar,
    color: '#ff9500',
    bgColor: 'rgba(255, 149, 0, 0.10)',
    borderColor: '#ff9500',
    description: 'Second-in-command',
    members: [
      { id: 1, name: 'Lu Alexander', badge: '103', unit: 'Patrol Division' },
      { id: 2, name: 'Darius Guevara', badge: '105', unit: 'Patrol Division' },
      { id: 3, name: 'Hanzo Martinez', badge: '126', unit: 'Patrol Division' },
      { id: 4, name: 'Selvador Tsushima', badge: '137', unit: 'Motorcycle Division' },
      { id: 5, name: 'Raffaelo Bergmann', badge: '184', unit: 'Interceptor Division' },
      { id: 6, name: 'Elliny Anik', badge: '141', unit: 'Patrol Division' },
    ],
  },
  {
    id: 8,
    rank: 'Staff Sergeant',
    icon: faUserTie,
    color: '#34c759',
    bgColor: 'rgba(52, 199, 89, 0.15)',
    borderColor: '#34c759',
    description: 'Senior NCO',
    members: [
      { id: 1, name: 'Filon Harris', badge: '104', unit: 'Patrol Division' },
      { id: 2, name: 'Kyo Yuma', badge: '124', unit: 'Motorcycle Division' },
      { id: 3, name: 'Tuco White', badge: '172', unit: 'Patrol Division' },
      { id: 4, name: 'Snape Torichilli', badge: '207', unit: 'Patrol Division' },
    ],
  },
  {
    id: 9,
    rank: 'Sergeant',
    icon: faUserTie,
    color: '#34c759',
    bgColor: 'rgba(52, 199, 89, 0.12)',
    borderColor: '#34c759',
    description: 'Supervises officers',
    members: [
      { id: 1, name: 'James Bogart', badge: '117', unit: 'Patrol Division' },
      { id: 2, name: 'MADRIDI', badge: '164', unit: 'Patrol Division' },
    ],
  },
  {
    id: 10,
    rank: 'Corporal',
    icon: faUserTie,
    color: '#34c759',
    bgColor: 'rgba(52, 199, 89, 0.10)',
    borderColor: '#34c759',
    description: 'Junior NCO',
    members: [
      { id: 1, name: 'Stive Roskovich', badge: '106', unit: 'Motorcycle Division' },
      { id: 2, name: 'Tyler Miller', badge: '113', unit: 'Patrol Division' },
      { id: 3, name: 'Zandy Dasilva', badge: '144', unit: 'Patrol Division' },
      { id: 4, name: 'Tokyo Montana', badge: '158', unit: 'Patrol Division' },
      { id: 5, name: 'Steve Colman', badge: '166', unit: 'Patrol Division' },
      { id: 6, name: 'Daniel Johnson', badge: '171', unit: 'Interceptor Division' },
      { id: 7, name: 'Philip James', badge: '182', unit: 'Patrol Division' },
      { id: 8, name: 'Oscan Roger', badge: '238', unit: 'Patrol Division' },
    ],
  },
  {
    id: 11,
    rank: 'Senior Officer',
    icon: faUserCheck,
    color: '#007aff',
    bgColor: 'rgba(0, 122, 255, 0.15)',
    borderColor: '#007aff',
    description: 'Experienced officer',
    members: [
      { id: 1, name: 'Rodrigo Martinez', badge: '139', unit: 'Patrol Division' },
      { id: 2, name: 'Rafael Deluca', badge: '206', unit: 'Patrol Division' },
      { id: 3, name: 'LEONARDO FERNANDEZ', badge: '220', unit: 'Motorcycle Division' },
      { id: 4, name: 'Weston Wolf', badge: '223', unit: 'Patrol Division' },
      { id: 5, name: 'Syconov Reaper', badge: '224', unit: 'Interceptor Division' },
      { id: 6, name: 'Weston Carter', badge: '231', unit: 'Patrol Division' },
      { id: 7, name: 'Rodrigo ZANZENA', badge: '239', unit: 'Patrol Division' },
      { id: 8, name: 'Lorenzo Thauvin', badge: '245', unit: 'Patrol Division' },
    ],
  },
  {
    id: 12,
    rank: 'Officer III',
    icon: faUser,
    color: '#007aff',
    bgColor: 'rgba(0, 122, 255, 0.12)',
    borderColor: '#007aff',
    description: 'Third rank officer',
    members: [
      { id: 1, name: 'Edouard Morgan', badge: '200', unit: 'Patrol Division' },
      { id: 2, name: 'Benji Lopez', badge: '256', unit: 'Patrol Division' },
    ],
  },
  {
    id: 13,
    rank: 'Officer II',
    icon: faUser,
    color: '#007aff',
    bgColor: 'rgba(0, 122, 255, 0.10)',
    borderColor: '#007aff',
    description: 'Second rank officer',
    members: [
      { id: 1, name: 'Yohan Carter', badge: '145', unit: 'Patrol Division' },
      { id: 2, name: 'Luis Ortega', badge: '234', unit: 'Patrol Division' },
      { id: 3, name: 'Milan Tyler', badge: '246', unit: 'Patrol Division' },
      { id: 4, name: 'Mathieu Murdock', badge: '251', unit: 'Patrol Division' },
      { id: 5, name: 'Alex Rodrigues', badge: '255', unit: 'Patrol Division' },
    ],
  },
  {
    id: 14,
    rank: 'Officer I',
    icon: faUser,
    color: '#007aff',
    bgColor: 'rgba(0, 122, 255, 0.08)',
    borderColor: '#007aff',
    description: 'First rank officer',
    members: [
      { id: 1, name: 'Louis Tate', badge: '129', unit: 'Patrol Division' },
      { id: 2, name: 'Hard Taylor', badge: '136', unit: 'Patrol Division' },
      { id: 3, name: 'Mario Lopez', badge: '152', unit: 'Patrol Division' },
      { id: 4, name: 'Frank Williams', badge: '235', unit: 'Patrol Division' },
      { id: 5, name: 'VANCE BLACKWOOD', badge: '263', unit: 'Patrol Division' },
      { id: 6, name: 'JAMES BENZ', badge: '264', unit: 'Patrol Division' },
    ],
  },
  {
    id: 15,
    rank: 'Cadet',
    icon: faGraduationCap,
    color: '#5856d6',
    bgColor: 'rgba(88, 86, 214, 0.15)',
    borderColor: '#5856d6',
    description: 'Officer in training',
    members: [
      { id: 1, name: 'Johne Wlyame', badge: '260', unit: 'Academy' },
      { id: 2, name: 'Bernardo Provenzano', badge: '261', unit: 'Academy' },
      { id: 3, name: 'Dieago Watson', badge: '262', unit: 'Academy' },
    ],
  },
  {
    id: 16,
    rank: 'Academy',
    icon: faGraduationCap,
    color: '#5856d6',
    bgColor: 'rgba(88, 86, 214, 0.10)',
    borderColor: '#5856d6',
    description: 'Recruits in training',
    members: [{ id: 1, name: 'Francisco Dalton', badge: '253', unit: 'Academy' }],
  },
];